name: Release
on: release

jobs:
  send:
    name: Send new verison
    runs-on: ubuntu-latest
    steps:
      - id: check_published
        name: Abort if action is not published
        uses: actions/checkout@master
        if: github.event.action == 'published'
      - name: HTTP client
        if: success()
        uses: swinton/httpie.action@1.0.6
        with:
          args: POST https://express.morzzz007.now.sh version=${GITHUB_REF} action=${{github.event.action}}
