name: Release
on: release

jobs:
  send:
    name: Send new verison
    runs-on: ubuntu-latest
    steps:
      - name: HTTP client
        if: github.event.action == 'published'
        run: curl -X POST -H "Authorization: ${ JWT_TOKEN }" -H "Content-Type: application/json" --data '{"action":"${{github.event.action}}", "version":"${GITHUB_REF}"}' https://express.morzzz007.now.sh
        env:
          JWT_TOKEN: ${{ secrets.JwtToken }}
