name: Release
on: release

jobs:
  send:
    name: Send new verison
    runs-on: ubuntu-latest
    steps:
      - name: HTTP client
        if: github.event.action == 'published'
        uses: swinton/httpie.action@1.0.6
        env:
          JWT_TOKEN: ${{ secrets.JwtToken }}
        with:
          args: --auth-type=hmac --auth=":${JWT_TOKEN}" POST https://express.morzzz007.now.sh version=${GITHUB_REF} action=${{github.event.action}}
